/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
* Updated HomeFrame.java with detailed Javadoc and inline comments
* (Original program logic unchanged as requested)
*/


/**
* HomeFrame serves as the main menu of the quiz application. It provides
* options to start the quiz or review previously saved quiz scores.
* <p>
* The frame also loads score history from a CSV file when initialized,
* allowing persistence of score data between program runs.
* </p>
/**
 *
 * @author Lenovo
 */
public class HomeFrame extends javax.swing.JFrame {
    /**
    * Stores the quiz scores from past sessions. Each score represents the
    * number of correct answers out of 5.
    */
    public static java.util.ArrayList<Integer> scoreHistory = new java.util.ArrayList<>();//Very impottant for storing the scores
/**
* File used for storing/reading quiz history so data is saved even when
* the program closes.
*/
    private static final String HISTORY_FILE = "quiz_history.csv";//Very important for the History File- can read and type in again even the program is shutted down
    

/**
* Constructs the HomeFrame UI and loads score history from file.
*/
    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        loadHistoryFromFile();//Connecting to the above, history storing 
        // Load stored score history on startup
        
        //Below is some GUI design, not important but beautiful
        getContentPane().setBackground(new java.awt.Color(224, 242, 221)); // 淡绿色背景
    
        java.awt.Color leafGreen = new java.awt.Color(69, 132, 73); // 叶片深绿
        java.awt.Color softWhite = new java.awt.Color(250, 250, 245); // 柔和白
    
        startQuizButton.setBackground(softWhite);
        startQuizButton.setForeground(leafGreen);
        startQuizButton.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 18));
        
        reviewHistoryButton.setBackground(softWhite);
        reviewHistoryButton.setForeground(leafGreen);
        reviewHistoryButton.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 18));
        
        
        jLabel1.setBackground(softWhite);
        jLabel1.setForeground(leafGreen);
        jLabel1.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 18));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(leafGreen, 2, true));
    
        // 圆角按钮效果
        startQuizButton.setFocusPainted(false);
        reviewHistoryButton.setFocusPainted(false);
        
        startQuizButton.addMouseListener(new HoverEffect(startQuizButton, softWhite, new java.awt.Color(239, 255, 239)));
        reviewHistoryButton.addMouseListener(new HoverEffect(reviewHistoryButton, softWhite, new java.awt.Color(239, 255, 239)));

    }

/**
* Loads quiz score history from the CSV file if it exists.
* Each line in the file contains a single integer score.
*/    
private void loadHistoryFromFile() {
java.io.File file = new java.io.File(HISTORY_FILE); // Reference file object


if (!file.exists()) return; // If no history exists, skip loading


try (java.util.Scanner sc = new java.util.Scanner(file)) { // Read file using Scanner
while (sc.hasNextLine()) {
String line = sc.nextLine(); // Read one line from CSV
String[] parts = line.split(","); // Split by comma


if (parts.length >= 1) {
// Parse score and add to history
scoreHistory.add(Integer.parseInt(parts[0]));
}
}
} catch (Exception e) {
System.out.println("Error reading history: " + e.getMessage()); // Print error message
}
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startQuizButton = new javax.swing.JButton();
        reviewHistoryButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startQuizButton.setText("Start Quiz now!");
        startQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startQuizButtonActionPerformed(evt);
            }
        });

        reviewHistoryButton.setText("Review History");
        reviewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewHistoryButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Are you 'green' enough?----    Quiz Check App");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Yunhao Sun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startQuizButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(reviewHistoryButton)))
                .addGap(179, 179, 179))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reviewHistoryButton)
                    .addComponent(startQuizButton))
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
* Action performed when Start Quiz button is clicked.
* Opens the QuizFrame and hides the current frame.
*/
    private void startQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startQuizButtonActionPerformed
        // TODO add your handling code here:
        new QuizFrame().setVisible(true);//These two lines are for frame changing
        this.setVisible(false);
    }//GEN-LAST:event_startQuizButtonActionPerformed
/**
* Action performed when Review History button is clicked.
* Displays stored quiz scores in a message dialog.
*/
    private void reviewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewHistoryButtonActionPerformed
        // TODO add your handling code here:
        if(scoreHistory.isEmpty()){//if there's nothing in the text stored before
        javax.swing.JOptionPane.showMessageDialog(this, "No quiz history yet!");//use dialog to print out the message
        } else {
        String result = "Your Scores:\n";//prepare for the message print below
        for(int i = 0; i < scoreHistory.size(); i++){//for loop to get the score
            int s = scoreHistory.get(i);
            result += s + "/5\n";// add score to the result
        }
        javax.swing.JOptionPane.showMessageDialog(this, result);//printout the result in the dialog
        
    }//Use dialog because of better GUI, learned from Youtube
    }//GEN-LAST:event_reviewHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

/**
* Provides hover effect for buttons by changing background color
* when mouse enters or leaves.
*/
class HoverEffect extends java.awt.event.MouseAdapter {
    private javax.swing.JButton btn;
    private java.awt.Color normal;
    private java.awt.Color hover;

    public HoverEffect(javax.swing.JButton btn, java.awt.Color normal, java.awt.Color hover) {
        this.btn = btn;
        this.normal = normal;
        this.hover = hover;
    }

    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        btn.setBackground(hover);
    }

    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        btn.setBackground(normal);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reviewHistoryButton;
    private javax.swing.JButton startQuizButton;
    // End of variables declaration//GEN-END:variables
}

